### PR TITLE
Fixed plain and unindexed array serialization in query params

### LINKED ISSUE #20: Wrong plain and unindexed array serialization in query params

### PR DESCRIPTION
**Pull request by asadali214**
Added url preprocessing and removed repeated encoding from library
Closes #20

### CODE REVIEW

File: src/Unirest/Request.php [hunk 1]
```diff
@@ -794,47 +794,32 @@ public static function getFormattedHeaders($headers)
...
-     * Ensure that a URL is encoded and safe to use with cURL
-     * @param  string $url URL to encode
-     * @return string
+     * Validates and processes the given Url to ensure safe usage with cURL.
+     * @param string $url The given Url to process
+     * @return string Pre-processed Url as string
+     * @throws Exception
      */
-    private static function encodeUrl($url)
+    public static function cleanUrl($url)
```
Comment (sufyankhanrao) [inline src/Unirest/Request.php]: cleanUrl is not what the function is doing rather it should be something validateAndCleanUrl or any other better name. As this method is doing two things i.e. validation of url and cleaning url in case of double slashes.

Comment (asadali214) [reply src/Unirest/Request.php]: since removing slashes are also same thing as validating the url hence renaming it to `validateUrl`

Comment (asadali214) [reply src/Unirest/Request.php:803]: since removing slashes are also same thing as validating the url hence renaming it to `validateUrl`

**Review by sufyankhanrao — APPROVED** [review]
Approved.
