### PR TITLE
fix(multipart-form-params): individual headers for multipart form params

### LINKED ISSUE #42: Individual content types for multipart form parameters
We need to add custom implementation for multipart form parameter to support individual content-type headers for each multipart form parameter, as curl does not support it out of the box.

### PR DESCRIPTION
**Pull request by Mohammad-Haris**
Closes #42

### CODE REVIEW

File: src/HttpClient.php [hunk 1]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+                $post_data .= file_get_contents($parameter->getFilename()) . "\r\n";
+            } elseif (isset($parameter["headers"])) {
+                $post_data .= 'Content-Disposition: form-data; name="' . $key . '"' . "\r\n";
+                foreach($parameter["headers"] as $headerKey => $headerValue) {
+                    $post_data .= $headerKey . ': ' . $headerValue . "\r\n\r\n";
+                }
+                if (isset($parameter["data"])) {
+                    $post_data .= $parameter["data"] . "\r\n";
+                }
+            } else {
```
Comment (asadali214) [inline src/HttpClient.php]: Refactor: This else block is not required

File: src/HttpClient.php [hunk 2]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+            $post_data .= '--' . $boundary . "\r\n";
+            if ($parameter instanceof \CURLFile) {
+                $post_data .= 'Content-Disposition: form-data; name="'
+                    . $key
+                    . '"; filename="' . basename($parameter->getFilename())
+                    . '"' . "\r\n";
+
+                $post_data .= 'Content-Type: ' . $parameter->getMimeType() . "\r\n\r\n";
+                $post_data .= file_get_contents($parameter->getFilename()) . "\r\n";
+            } elseif (isset($parameter["headers"])) {
```
Comment (asadali214) [inline src/HttpClient.php]: Refactor: the condition `isset($parameter["headers"])` is always true

File: src/HttpClient.php [hunk 3]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+                $post_data .= 'Content-Disposition: form-data; name="' . $key . '"' . "\r\n";
+                foreach($parameter["headers"] as $headerKey => $headerValue) {
+                    $post_data .= $headerKey . ': ' . $headerValue . "\r\n\r\n";
```
Comment (asadali214) [inline src/HttpClient.php]: This line adds additional `\r\n` after each header kindly remove extra line between each header

File: src/HttpClient.php [hunk 4]
```diff
@@ -333,23 +380,21 @@ public function getInfo(?int $option = null)
         return curl_getinfo($this->handle, $option);
     }
 
-    protected function getFormattedHeaders(RequestInterface $request): array
+    protected function getFormattedHeaders(RequestInterface $request, $multiPartRequestHeaders = []): array
```
Comment (asadali214) [inline src/HttpClient.php]: rename the argument: `multiPartRequestHeaders` to `additionalHeaders`

File: src/HttpClient.php [hunk 5]
```diff
@@ -134,12 +179,14 @@ protected function setCurlOptions($handle, RequestInterface $request): void
             $queryUrl .= http_build_query(Request::buildHTTPCurlQuery($body));
```
Comment (asadali214) [inline src/HttpClient.php]: Why are you not using `$body["data"]` instead of `$body` here?
This will change the behavior of query params and break the existing applications

File: src/HttpClient.php [hunk 6]
```diff
@@ -123,9 +168,9 @@ protected function setCurlOptions($handle, RequestInterface $request): void
             }
 
             if (!is_null($body)) {
```
Comment (asadali214) [inline src/HttpClient.php]: use `$body["data"]` instead of `$body` in this if condition

File: src/HttpClient.php
Comment (asadali214) [inline src/HttpClient.php:1]: use `list($data, $headers) = getBody($request);` to assign multiple parameters of the body array at once on line 159

File: src/HttpClient.php [hunk 7]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+                }
+            } else {
+                // Can we get arrays here as parameters?
+                if (!is_array($parameter)) {
+                    $post_data .= 'Content-Disposition: form-data; name="' . $key . '"' . "\r\n\r\n";
+                    $post_data .= $parameter . "\r\n";
+                }
+            }
+            if ($i == $length) {
+                $post_data .= '--' . $boundary . '--' . "\r\n";
```
Comment (asadali214) [inline src/HttpClient.php]: This check `$i == $length` is only adding the boundary at the end, whilst you can add that boundary after the foreach loop ends

File: src/HttpClient.php [hunk 8]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+            }
+            $i++;
+        }
+
+        $headers = [];
```
Comment (asadali214) [inline src/HttpClient.php]: Refactor: use inline array initialization

File: src/HttpClient.php (hunk 7 above)
Comment (asadali214) [reply src/HttpClient.php]: This would also make the variables $i and $length unused

File: src/HttpClient.php (hunk 2 above)
Comment (asadali214) [reply src/HttpClient.php]: Tip: use a continue; statement at the end of above if block and remove the else if condition altogether

File: tests/RequestTest.php
Comment (asadali214) [inline tests/RequestTest.php:1]: Do not update any tests, updating these tests means that we are adding breaking changes, which we are not!
If these tests started failing that might mean that you have added a bug in the implementation

File: src/HttpClient.php [hunk 9]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
     protected function getBody(RequestInterface $request)
```
Comment (asadali214) [inline src/HttpClient.php]: Add array as functions return type

File: src/HttpClient.php [hunk 10]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
         if (empty($encodedBody)) {
-            return $multipartParameters;
+            return $this->createMultiPartFormData($multipartParameters);
         }
         foreach (explode('&', $encodedBody) as $param) {
             $keyValue = explode('=', $param);
             $multipartParameters[urldecode($keyValue[0])] = urldecode($keyValue[1]);
         }
-        return $multipartParameters;
+        return $this->createMultiPartFormData($multipartParameters);
```
Comment (asadali214) [inline src/HttpClient.php:108]: Add array as functions return type

File: src/HttpClient.php [hunk 11]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+    }
+
+    private function createMultiPartFormData($multipartParameters)
```
Comment (asadali214) [inline src/HttpClient.php]: Add array as functions return type

File: src/HttpClient.php [hunk 12]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+                $post_data .= 'Content-Disposition: form-data; name="'
+                    . $key
+                    . '"; filename="' . basename($parameter->getFilename())
+                    . '"' . "\r\n";
+
+                $post_data .= 'Content-Type: ' . $parameter->getMimeType() . "\r\n\r\n";
+                $post_data .= file_get_contents($parameter->getFilename()) . "\r\n";
+            } elseif (isset($parameter["headers"])) {
+                $post_data .= 'Content-Disposition: form-data; name="' . $key . '"' . "\r\n";
+                foreach($parameter["headers"] as $headerKey => $headerValue) {
```
Comment (asadali214) [inline src/HttpClient.php]: add a space after foreach keyword

File: src/HttpClient.php [hunk 13]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
+    private function createMultiPartFormData($multipartParameters)
+    {
+        $i = 1;
+        $length = count($multipartParameters);
+        $boundary = uniqid();
+        $post_data = '';
+
+        foreach ($multipartParameters as $key => $parameter) {
+            $post_data .= '--' . $boundary . "\r\n";
+            if ($parameter instanceof \CURLFile) {
```
Comment (asadali214) [inline src/HttpClient.php]: add CURLFile import instead of using a `\` behind it

File: src/HttpClient.php [hunk 14]
```diff
@@ -88,24 +88,69 @@ protected function initializeHandle()
...
-            return $encodedBody;
+            return [ 'data' => $encodedBody, 'headers' => [ 'content-type' => 'application/x-www-form-urlencoded' ] ];
         }
         if (empty($encodedBody)) {
-            return $multipartParameters;
+            return $this->createMultiPartFormData($multipartParameters);
         }
         foreach (explode('&', $encodedBody) as $param) {
             $keyValue = explode('=', $param);
             $multipartParameters[urldecode($keyValue[0])] = urldecode($keyValue[1]);
```
Comment (asadali214) [inline src/HttpClient.php]: Since you have updated the structure for each multipart form param, please depict that here. Instead of setting `urldecode($keyValue[1])` directly, set `['data' => urldecode($keyValue[1]), 'headers' => [] ]`

File: src/HttpClient.php (hunk 12 above)
Comment (asadali214) [reply src/HttpClient.php]: This is also failing the linting tests in all PHP versions

File: src/HttpClient.php (hunk 11 above)
Comment (asadali214) [inline src/HttpClient.php]: create this function as protected, which will enable us to write its unit tests later

File: src/HttpClient.php (hunk 12 above)
Comment (Mohammad-Haris) [reply src/HttpClient.php]: Lint was passing, it might be failing after your commit.

File: src/HttpClient.php (hunk 7 above)
Comment (Mohammad-Haris) [reply src/HttpClient.php]: Micro-optimization with no functional change. Still modifying it for your convenience as you guys are going to manage it afterwards.

**Review by asadali214 — APPROVED** [review]
Approved
